name: 'baiduPush'

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'run script'
        run: npm install && npm run baiduPush 