# 自定义当前执行文件的名称
name: vuepress
# 整个流程在main分支发生push事件时触发
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 运行在ubuntu-latest环境的虚拟机中
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    # 获取仓库源码
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }} # 步骤2
      uses: actions/setup-node@v1 # 作用：安装nodejs
      with:
        node-version: ${{ matrix.node-version }} # 版本
    # 构建和部署
    - name: Deploy
      env: # 环境变量
        GITHUB_TOKEN: ${{ secrets.vuepress_actions_access_token }} # 在仓库中配置的token
      run: npm install && npm run deploy
